(()=>{const challenges=[
{q:'Light and darkness are...',p:'Choose the pair that means opposite ideas.',a:['synonyms','antonyms','homophones'],ok:1},
{q:'Which word is a synonym for bright?',p:'A synonym has a similar meaning.',a:['shiny','sleepy','heavy'],ok:0},
{q:'Which pair is a homophone?',p:'Listen for words that sound alike.',a:['light / dark','sea / see','day / night'],ok:1},
{q:'What is an antonym of day?',p:'Think about the opposite.',a:['morning','night','sun'],ok:1},
{q:'Where is the suffix in “lightness”?',p:'A suffix is added to the end of a word.',a:['light','-ness','li-'],ok:1},
{q:'Which punctuation ends a question?',p:'You use it when you ask something.',a:['.','!','?'],ok:2}];
let i=0,earned=0;const $=id=>document.getElementById(id);function show(){const c=challenges[i];$('challengeNumber').textContent='Challenge '+(i+1)+' of '+challenges.length;$('question').textContent=c.q;$('prompt').textContent=c.p;$('feedback').textContent='';$('answers').innerHTML=c.a.map((x,n)=>'<button class="answer" data-n="'+n+'" type="button">'+x+'</button>').join('')}
function burst(){const b=document.createElement('div');b.className='burst';b.textContent='+25 XP ✨';b.style.left=(35+Math.random()*25)+'%';b.style.top='55%';document.body.appendChild(b);setTimeout(()=>b.remove(),900)}
$('answers').addEventListener('click',e=>{const b=e.target.closest('.answer');if(!b)return;const n=Number(b.dataset.n),c=challenges[i];document.querySelectorAll('.answer').forEach(x=>x.disabled=true);if(n===c.ok){b.classList.add('correct');$('feedback').textContent='🎉 Correct! +25 XP';window.GEI.state.xp+=25;earned++;window.GEI.save();window.GEI.render();window.GEI.sound('correct');burst();$('challengeCard').classList.add('flash');setTimeout(()=>$('challengeCard').classList.remove('flash'),650);setTimeout(()=>{if(i<challenges.length-1){i++;show()}else complete()},900)}else{b.classList.add('wrong');$('feedback').textContent='💡 Not quite. Try the idea again.';window.GEI.sound('wrong');setTimeout(()=>{document.querySelectorAll('.answer').forEach(x=>x.disabled=false)},500)}});function complete(){if(!window.GEI.state.completedDays.includes(1))window.GEI.state.completedDays.push(1);window.GEI.state.level=Math.max(window.GEI.state.level,2);window.GEI.save();window.GEI.sound('complete');$('challengeCard').innerHTML='<div class="hero"><p class="eyebrow">LEVEL 1 COMPLETE</p><h2>🏆 Fantastic work, '+(window.GEI.state.name||'Explorer')+'!</h2><p>You mastered the Genesis / Light foundation and earned '+earned*25+' XP.</p><p><strong>Next: Level 2 — Dam / Firmament.</strong></p><p class="notice">🔓 Level 2 is now unlocked. Level 2 will be added as the next milestone.</p><button class="secondary" id="backHome" type="button">← Academy Home</button></div>';window.GEI.render();$('backHome').onclick=()=>location.href='index.html'}show();})();